version: '3.6'

services:
  db:
    image: postgres:13.2
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: cqrs
      POSTGRES_USER: cqrs
      POSTGRES_PASSWORD: cqrs
      PGDATA: /var/lib/postgresql/data
    tmpfs: /var/lib/postgresql/data

  go:
    image: golang:1.16.5
    volumes:
      - ./:/src
      - ./_example/migrations:/var/migrations
      - go-deps:/go/pkg
    working_dir: /src
    ports:
    - 8085:80
    depends_on: 
      - db
    environment:
      ENVIRONMENT: "development"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "cqrs"
      DB_NAME: "cqrs"
      DB_PASS: "cqrs"
      SECRET_KEY: "secret"
      PORT: "80"
    command: ["bash", "-c", "cd _example; go run example"]

volumes:
  go-deps: {}
