version: '3'

tasks:
  test:
    cmds:
      - go test ./... -tags=unit
    sources:
      - ./**/*.go

  test:integration:
    cmds:
      - docker-compose run --rm go go test ./... {{ .CLI_ARGS }}

  test:system:
    deps: [render-example]
    cmds:
      - docker-compose run --rm go bash -c "cd _example; go run ."

  build:
    cmds:
      - go build .
    sources:
      - ./**/*.go

  render-example:
    cmds:
      - rm -rf ./_example
      - cd gen; go run . init -module=example -root=../_example -example=true
      - cd _example; go mod tidy
