---
routes:
- path: /rest/v1/auth/login
  method: POST
  query: 
    question: example/users/queries.Login
    answer: example/users/readmodels.Authentication

- path: /rest/v1/auth/register
  method: POST
  command: example/users/commands.Register

- path: /rest/v1/users/:ID
  method: GET
  query:
    question: example/users/queries.User
    answer: example/users/entities.User
  middleware: ["Auth"]

- path: /rest/v1/roles/:ID
  method: GET
  query:
    question: example/users/queries.Role
    answer: example/users/entities.Role
  middleware: ["Auth"]

