---
routes:
- path: /rest/v1/auth/login
  method: POST
  query: 
    question: example/users/queries.Login
    answer: example/users/readmodels.Authentication

- path: /rest/v1/auth/register
  method: POST
  command: example/users/commands.Register

- path: /rest/v1/users/:email
  method: GET
  query:
    question: example/users/queries.User
    answer: example/users/entities.User
