---
routes:
- path: /rest/v1/auth/login
  method: POST
  query: 
    question: {{ .Module }}/users/queries.Login
    answer: {{ .Module }}/users/readmodels.Authentication

- path: /rest/v1/auth/register
  method: POST
  command: {{ .Module }}/users/commands.Register

- path: /rest/v1/users/:ID
  method: GET
  query:
    question: {{ .Module }}/users/queries.User
    answer: {{ .Module }}/users/entities.User
  middleware: ["Auth"]

- path: /rest/v1/roles/:ID
  method: GET
  query:
    question: {{ .Module }}/users/queries.Role
    answer: {{ .Module }}/users/entities.Role
  middleware: ["Auth"]

- path: /rest/v1/users
  method: GET
  query:
    question: {{ .Module }}/users/queries.Users
    answer: {{ .Module }}/internal/support.PaginatedQuery
  middleware: ["Auth"]

- path: /rest/v1/roles
  method: GET
  query:
    question: {{ .Module }}/users/queries.Roles
    answer: {{ .Module }}/internal/support.PaginatedQuery
  middleware: ["Auth"]

- path: /rest/v1/roles
  method: POST
  command: {{ .Module }}/users/commands.CreateRole
  middleware: ["Auth"]

- path: /rest/v1/users
  method: PUT
  command: {{ .Module }}/users/commands.UpdateUser
  middleware: ["Auth"]

- path: /rest/v1/roles
  method: PUT
  command: {{ .Module }}/users/commands.UpdateRole
  middlware: ["Auth"]
